### ISSUE TITLE
Module 14: Shared Web Worker not in Edge, removed from WebKit

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftLearning/20480-Programming-in-HTML5-with-JavaScript-and-CSS3#100]
The SharedWorker is [not planned with Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/sharedwebworkers), and [removed from WebKit](http://webkit.org/status.html#feature-shared-web-workers).

Instead, the **Service Worker** should be added. This is also related to #93 with the request to remove the *application cache*. The [Service Worker](https://w3c.github.io/ServiceWorker/) is a replacement for the application cache.

**Comment by ChrisHowd** [comment]
MS is closing this issue.
