### ISSUE TITLE
Instruction step seems to accomplish nothing except making you bang your head on desk

### ISSUE THREAD

**Issue by CentriqTraining** [MicrosoftLearning/20480-Programming-in-HTML5-with-JavaScript-and-CSS3#105]
https://github.com/MicrosoftLearning/20480-Programming-in-HTML5-with-JavaScript-and-CSS3/blob/master/Instructions/20480C_MOD13_LAK.md

Task 3 Step 5
Find this method.

Task 3 Step 6
Now go find something else.

Should remove?

**Comment by christiannagel** [comment]
Do you mean task 3 of exercise 1?
In step 7 you invoke the method you found in step 5, so this step shouldn't be removed. Instead, more explanation could be added.

**Comment by ChrisHowd** [comment]
MS is closing this issue.
