### ISSUE TITLE
Comparing A, B, C versions

### ISSUE THREAD

**Issue by MariuzM** [MicrosoftLearning/20480-Programming-in-HTML5-with-JavaScript-and-CSS3#108]
So i'm learning the C version, but i also have access to A, B. On the C version there is no more jQuery and then we have something new: NodeJS, NPM, Webpack. So my questions is, because Microsoft has released a new version of their documentation (C) ant it does not include jQuery any more, will there be jQuery questions in the current exams?

**Comment by christiannagel** [comment]
I don't think there are - but the exam retires on January 31, 2021 anyway. https://www.microsoft.com/en-us/learning/exam-70-480.aspx
