### ISSUE TITLE
Module 01 Solution File errors prevent running as instructed.  Had to restore Microsoft.Web.Infrastructure 

### ISSUE THREAD

**Issue by DDHudson** [MicrosoftLearning/20480-Programming-in-HTML5-with-JavaScript-and-CSS3#110]
Module 01 Had to restore Microsoft.Web.Infrastructure.

**Comment by michaelsnp** [comment]
Hi,

I solve this problem installing the ASP.NET MVC 3 Tools from this link:

https://www.microsoft.com/en-us/download/details.aspx?id=1491

Then you can run the project without any problem,

I hope it can help,

Michael Nuñez
www.linkedin.com/in/-michael-nunez

**Comment by ChrisHowd** [comment]
MS is closing this issue.
