### ISSUE TITLE
Module 15: npm installer may have changed its behavior to break the instructions/code flow?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/20480-Programming-in-HTML5-with-JavaScript-and-CSS3#123]
In Module 15/Exercise 1/Task 1:

- Step 9, this command works: **npm install babel-core babel-loader babel-preset-es2015 webpack --save-dev** ...BUT, the changes it makes to the **package.json** file no longer seem to allow the command later in Task 2/Step 1 (**npm run webpack**) to run successfully.

- Instead, one receives an error **npm ERR! missing script: webpack**

- One way to work around this problem is to modify the **package.json** file after the initial npm install to be:

{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "scripts": {
    "webpack": "webpack"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-es2015": "^6.24.1",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2"
  }
}

This seems to allow one to proceed successfully to the end of the module.

**Comment by m8rvil** [comment]
I also received an error in the demo : Demonstration: Using Webpack and Babel to Build a JavaScript App
I note the following issues: 

Set Up Babel and Webpack on step 9 
In the app.js file where do we add the following two lines?
 require('babel-polyfill');
 require('isomorphic-fetch');

Build and Run the App
On step 1 ; At the command prompt, run the following command: npm run webpack
I get the following error : 

13 verbose stack Error: asp.net@1.0.0 webpack: `webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid asp.net@1.0.0
15 verbose cwd C:\Program Files\Microsoft Learning\20480C\Allfiles\Mod15\DemoCode\build-tutorial\build-tutorial
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "webpack"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error asp.net@1.0.0 webpack: `webpack`
22 error Exit status 1
23 error Failed at the asp.net@1.0.0 webpack script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

And also Field Browser does not contain a valid alias configuration  
C:// Program Files.../src doesn't exist 
.js
Field Browser does not contain a valid alias configuration  
C:// Program Files.../build-tutorial/src.js doesn't exist 
.json
Field Browser does not contain a valid alias configuration  
C:// Program Files.../build-tutorial/src.json doesn't exist 
.wasm
Field Browser does not contain a valid alias configuration  
C:// Program Files.../build-tutorial/src.wasm doesn't exist 
as directory 
C:// Program Files.../build-tutorial/src doesn't exist

**Comment by ChrisHowd** [comment]
MS is closing this issue.
