### ISSUE TITLE
RegistrationController Contains Incorrect RegEx for Email

### ISSUE THREAD

**Issue by sdkibb** [MicrosoftLearning/20480-Programming-in-HTML5-with-JavaScript-and-CSS3#133]
Email validation RegEx in RegistrationController.cs doesn't match the browser definition for type=email input validation. Browsers allow the name@site, I assume to account for the format of name@IP which has no TLD and is still a valid email.  It would seem the backend validation should match the front end browser validation on type=email and allow an email with no TLD. Unless I'm missing something and there a reason this discrepancy exists? Can submit a PR with proposed changes if it's appropriate.

**Comment by ChrisHowd** [comment]
MS is closing this issue.
