### ISSUE TITLE
Module 9: The application cache is deprecated

### ISSUE THREAD

**Issue by rofr** [MicrosoftLearning/20480-Programming-in-HTML5-with-JavaScript-and-CSS3#93]
"This feature has been removed from the Web standards"
https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

**Comment by gyssels** [comment]
DOESN'T WORK ANYMORE, please  remove from slides.
Deprecated
This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

**Comment by gyssels** [comment]
LAB on the manifest (lab 9, exercise 1) should be removed
Task 5 of exercise 2 should be removed

ex1/task 1: should be updated to the current edge
ex2/task6: should be updated to the current edge

**Comment by ChrisHowd** [comment]
MS is closing this issue.
